---

- name: Add Docker key
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install packages
  become: yes
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
    state: present
    update_cache: yes

- name: Enable docker service
  become: yes
  service:
    name: docker
    enabled: yes
    state: started